### LOGIN TEST
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "admin@ysq.com",
  "password": "123456"
}

### LOGIN PENGAJAR
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "Maya.pengajar@ysq.com",
  "password": "123456"
}

### LOGIN SANTRI
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "santri1@ysq.com",
  "password": "123456"
}

### LOGIN SANTRI
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "santri1@ysq.com",
  "password": "123456"
}

### Pendaftar Daftar
POST http://localhost:5000/pendaftar/daftar
Content-Type: application/json

{
  "nama": "Yesi Mediatama",
  "tempat_lahir": "Bogor",
  "tanggal_lahir": "2005-11-20",
  "email": "yesi@gmail.com",
  "no_wa": "08102097658"
}

### Admin Terima Pendaftar
PUT http://localhost:5000/pendaftar/terima/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NjM1NTI2NjYsImV4cCI6MTc2MzYzOTA2Nn0.4vnq2rsr0MYsMfj_SIqwxmuKga6aJg78e0-dVi8oBtM
Content-Type: application/json
